django_simple_forum/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'django_simple_forum.views.index', name='forum-index'),
    url(r'^(\d+)/$', 'django_simple_forum.views.forum', name='forum-detail'),
    url(r'^topic/(\d+)/$', 'django_simple_forum.views.topic', name='topic-detail'),
    url(r'^reply/(\d+)/$', 'django_simple_forum.views.post_reply', name='reply'),
    url(r'newtopic/(\d+)/$', 'django_simple_forum.views.new_topic', name='new-topic'),
)

kyl/urls.py
from django.conf.urls import url,include
from kyl import views

urlpatterns = [
    url(r'^$', views.homepage , name = 'homepage'),
    url(r'^contact$', views.contact , name = 'contact'),
    url(r'^newsfeed$', views.rssfeed , name = 'rssfeed'),
    url(r'^login$', views.user_login , name = 'login'),
    url(r'^logout$', views.user_logout , name = 'logout'),
    url(r'^signup$', views.register , name = 'signup'),
    url(r'^users/verify_email/(?P<key>.+)$', views.verify_email , name = 'signup'),
    url(r'^leadership/modi$', views.leadership_modi , name = 'leadership_modi'),
    url(r'^leadership/obama$', views.leadership_obama , name = 'leadership_obama'),
]

politics/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('kyl.urls' , namespace="kyl")),
    url(r'^forums/', include('django_simple_forum.urls' , namespace="forums")),
]  + static(settings.STATIC_URL)

django_simple_forum/models.py
from django.db import models
from kyl.models import User
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

class Forum(models.Model):
    title = models.CharField(max_length=60)
    description = models.TextField(blank=True, default='')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, blank=True, null=True)

    def __unicode__(self):
        return self.title

    def num_posts(self):
        return sum([t.num_posts() for t in self.topic_set.all()])

    def last_post(self):
        if self.topic_set.count():
            last = None
            for t in self.topic_set.all():
                l = t.last_post()
                if l:
                    if not last: last = l
                    elif l.created > last.created: last = l
            return last

class Topic(models.Model):
    title = models.CharField(max_length=60)
    description = models.TextField(max_length=10000, blank=True, null=True)
    forum = models.ForeignKey(Forum)
    created = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    closed = models.BooleanField(blank=True, default=False)

    def num_posts(self):
        return self.post_set.count()

    def num_replies(self):
        return max(0, self.post_set.count() - 1)

    def last_post(self):
        if self.post_set.count():
            return self.post_set.order_by("created")[0]

    def __unicode__(self):
        return unicode(self.creator) + " - " + self.title

class Post(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey(Topic)
    body = models.TextField(max_length=10000)
    user_ip = models.GenericIPAddressField(blank=True, null=True)

    def __unicode__(self):
        return u"%s - %s - %s" % (self.creator, self.topic, self.title)

    def short(self):
        return u"%s - %s\n%s" % (self.creator, self.title, self.created.strftime("%b %d, %I:%M %p"))

    short.allow_tags = True


class ProfaneWord(models.Model):
    word = models.CharField(max_length=60)

    def __unicode__(self):
        return self.word

django_simple_forum/forms.py
from django import forms
from django_simple_forum.models import Topic, Post, ProfaneWord

from settings import *

class TopicForm(forms.ModelForm):

    title = forms.CharField(max_length=60, required=True)

    class Meta():
        model = Topic
        exclude = ('creator','updated', 'created', 'closed', 'forum',)


class PostForm(forms.ModelForm):
    
    class Meta():
        model = Post
        exclude = ('creator', 'updated', 'created','topic', 'user_ip',)

    def clean_body(self):
        body = self.cleaned_data["body"]

        if DJANGO_SIMPLE_FORUM_FILTER_PROFANE_WORDS:
            profane_words = ProfaneWord.objects.all() 
            bad_words = [w for w in profane_words if w.word in body.lower()]

            if bad_words:
                raise forms.ValidationError("Bad words like '%s' are not allowed in posts." % (reduce(lambda x,y: "%s,%s" % (x,y),bad_words)))
        
        return body

django_simple_forum/views.py
from django.template import RequestContext

from django.forms import models as forms_models

from django.http import HttpResponseRedirect

from django.shortcuts import render_to_response, get_object_or_404

from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.core.context_processors import csrf

from django_simple_forum.models import Forum, Topic, Post
from django_simple_forum.forms import TopicForm, PostForm

#from guest.decorators import guest_allowed, login_required
from django.contrib.auth.decorators import login_required


from django.template import RequestContext

from settings import *

def index(request):
    """Main listing."""
    forums = Forum.objects.all()
    return render_to_response("django_simple_forum/list.html", {'forums': forums, 
                                'user': request.user}, 
                                context_instance=RequestContext(request))


def add_csrf(request, ** kwargs):
    d = dict(user=request.user, ** kwargs)
    d.update(csrf(request))
    return d

def mk_paginator(request, items, num_items):
    """Create and return a paginator."""
    paginator = Paginator(items, num_items)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        items = paginator.page(page)
    except (InvalidPage, EmptyPage):
        items = paginator.page(paginator.num_pages)
    return items

def forum(request, forum_id):
    """Listing of topics in a forum."""
    topics = Topic.objects.filter(forum=forum_id).order_by("-created")
    topics = mk_paginator(request, topics, DJANGO_SIMPLE_FORUM_TOPICS_PER_PAGE)

    forum = get_object_or_404(Forum, pk=forum_id)

    return render_to_response("django_simple_forum/forum.html", add_csrf(request, topics=topics, pk=forum_id, forum=forum),
                              context_instance=RequestContext(request))

def topic(request, topic_id):
    """Listing of posts in a topic."""
    posts = Post.objects.filter(topic=topic_id).order_by("created")
    posts = mk_paginator(request, posts, DJANGO_SIMPLE_FORUM_REPLIES_PER_PAGE)
    topic = Topic.objects.get(pk=topic_id)
    return render_to_response("django_simple_forum/topic.html", add_csrf(request, posts=posts, pk=topic_id,
        topic=topic), context_instance=RequestContext(request))

@login_required
def post_reply(request, topic_id):
    form = PostForm()
    topic = Topic.objects.get(pk=topic_id)
    
    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():

            post = Post()
            post.topic = topic
            post.title = form.cleaned_data['title']
            post.body = form.cleaned_data['body']
            post.creator = request.user
            post.user_ip = request.META['REMOTE_ADDR']

            post.save()

            return HttpResponseRedirect(reverse('forums:topic-detail', args=(topic.id, )))

    return render_to_response('django_simple_forum/reply.html', {
            'form': form,
            'topic': topic,
        }, context_instance=RequestContext(request))

@login_required
def new_topic(request, forum_id):
    form = TopicForm()
    forum = get_object_or_404(Forum, pk=forum_id)
    
    if request.method == 'POST':
        form = TopicForm(request.POST)

        if form.is_valid():

            topic = Topic()
            topic.title = form.cleaned_data['title']
            topic.description = form.cleaned_data['description']
            topic.forum = forum
            topic.creator = request.user

            topic.save()

            return HttpResponseRedirect(reverse('forum-detail', args=(forum_id, )))

    return render_to_response('django_simple_forum/new-topic.html', {
            'form': form,
            'forum': forum,
        }, context_instance=RequestContext(request))

django_simple_forum/templates/django_simple_forum/forum.html
<!-- Threads  -->
<a id="new_topic" class="button" href="{% url 'forums:new-topic' pk %}">Start New Topic</a>
<br />
<br />

<div id="list">
<table border="0" cellpadding="4" width="100%">
    <tr>
        <td>Topics</td>
        <td>Replies</td>
        <td>Last post</td>
        <td></td>
    </tr>

    {% for topic in topics.object_list %}
    <tr>
        <td {% if forloop.last %}class="last"{% endif %}>
        <div class="title"> <a href="{% url 'forums:topic-detail' topic.pk %}">{{ topic.title }}</a>
            </div></td>
        <td {% if forloop.last %}class="last"{% endif %}>{{ topic.num_replies }}</td>
        <td {% if forloop.last %}class="last"{% endif %}>
            {{ topic.last_post.short|linebreaksbr }}</td>
        <td {% if forloop.last %}class="last"{% endif %}>
            <a class="button" href="{% url 'forums:topic-detail' topic.pk %}">VIEW</a>
        </td>
    </tr>

    {% endfor %}
</table>
</div>

<!-- Next/Prev page links  -->
{% if topics.object_list and topics.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if topics.has_previous %}
            <a href= "?page={{ topics.previous_page_number }}">previous &lt;&lt; </a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ topics.number }} of {{ topics.paginator.num_pages }}
        </span>

        {% if topics.has_next %}
            <a href="?page={{ topics.next_page_number }}"> &gt;&gt; next</a>
        {% endif %}
    </span>
</div>
{% endif %}

django_simple_forum/templates/django_simple_forum/list.html
<!-- Forums  -->
<div id="list">
    <table border="0" cellpadding="4" width="100%">
        <tr>
            <td></td>
            <td>Posts</td>
            <td>Last post</td>
            <td></td>
        </tr>
        {% for forum in forums %}
            <tr>
                <td {% if forloop.last %}class="last"{% endif %}>
                    <div class="title"> <a href="{% url 'forums:forum-detail' forum.pk %}">{{ forum.title }}</a></div>
                </td>
                <td {% if forloop.last %}class="last"{% endif %}>{{ forum.num_posts }}</td>
                <td {% if forloop.last %}class="last"{% endif %}>
                    {{ forum.last_post.short|linebreaksbr }}</td>
                <td {% if forloop.last %}class="last"{% endif %}>
                    <a class="button" href="{% url 'forums:forum-detail' forum.pk %}">VIEW</a>
                </td>
            </tr>
        {% endfor %}
</div>

django_simple_forum/templates/django_simple_forum/new-topic.html
<form action="{% url 'forums:new-topic' forum.id %}" method="POST">
    {% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

django_simple_forum/templates/django_simple_forum/reply.html
<form action="{% url 'forums:reply' topic.id %}" method="POST">
    {% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

django_simple_forum/templates/django_simple_forum/topic.html
<!-- Posts  -->
<div class="ttitle">{{ topic.title }}</div>
<div id="list">

    {% for post in posts.object_list %}
        <div class="post">
            <span class="title">{{ post.title }}</span><br />
            by {{ post.creator }} | <span class="date">{{ post.created }}</span> <br /><br />
            {{ post.body }} <br />
        </div>
    {% endfor %}
</div>

<!-- Next/Prev page links  -->
{% if posts.object_list and posts.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href= "?page={{ posts.previous_page_number }}">previous &lt;&lt; </a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ posts.number }} of {{ topics.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}"> &gt;&gt; next</a>
        {% endif %}
    </span>
</div>
{% endif %}
<a class="button" href="{% url 'forums:reply' pk %}">Reply</a>