django_simple_forum/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'django_simple_forum.views.index', name='forum-index'),
    url(r'^(\d+)/$', 'django_simple_forum.views.forum', name='forum-detail'),
    url(r'^topic/(\d+)/$', 'django_simple_forum.views.topic', name='topic-detail'),
    url(r'^reply/(\d+)/$', 'django_simple_forum.views.post_reply', name='reply'),
    url(r'newtopic/(\d+)/$', 'django_simple_forum.views.new_topic', name='new-topic'),
)

kyl/urls.py
from django.conf.urls import url,include
from kyl import views

urlpatterns = [
    url(r'^$', views.homepage , name = 'homepage'),
    url(r'^contact$', views.contact , name = 'contact'),
    url(r'^newsfeed$', views.rssfeed , name = 'rssfeed'),
    url(r'^login$', views.user_login , name = 'login'),
    url(r'^logout$', views.user_logout , name = 'logout'),
    url(r'^signup$', views.register , name = 'signup'),
    url(r'^users/verify_email/(?P<key>.+)$', views.verify_email , name = 'signup'),
    url(r'^leadership/modi$', views.leadership_modi , name = 'leadership_modi'),
    url(r'^leadership/obama$', views.leadership_obama , name = 'leadership_obama'),
]

politics/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('kyl.urls' , namespace="kyl")),
    url(r'^forums/', include('django_simple_forum.urls' , namespace="forums")),
]  + static(settings.STATIC_URL)

templates/base.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}

<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Politics Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static "css/bootstrap-3.1.1.min.css" %}" rel="stylesheet" type="text/css">
<!-- Custom Theme files -->
<link href="{% static "css/owl.carousel.css" %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static "css/style.css" %}" rel='stylesheet' type='text/css' />   
<script src="{% static "js/jquery.min.js" %}" > </script>
<script type="text/javascript" src="{% static "js/move-top.js" %}"></script>
<script type="text/javascript" src="{% static "js/easing.js" %}"></script>
<link rel="stylesheet" href="{% static "css/flexslider.css" %}" type="text/css" media="screen" />
<!--/script-->
<link href='//fonts.googleapis.com/css?family=Hammersmith+One' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic,700' rel='stylesheet' type='text/css'>
<script type="text/javascript">
            jQuery(document).ready(function($) {
                $(".scroll").click(function(event){     
                    event.preventDefault();
                    $('html,body').animate({scrollTop:$(this.hash).offset().top},900);
                });
            });
</script>
{% block extrahead %} {% endblock %}
</head>
<body>
    <div class="header" id="home">
        <div class="content white">
            <nav class="navbar navbar-default" role="navigation">
            <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'kyl:homepage' %}">Know Thy Leader  </a>
            </div>
            <!--/.navbar-header-->
        
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'kyl:homepage' %}">Home</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Forum<b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-2">
                                <div class="row">
                                    <div class="party">
                                        <ul class="multi-column-dropdown">
                                            <li><a href="about.html">History</a></li>
                                            <li class="divider"></li>
                                            <li><a href="about.html">Philosophy</a></li>
                                            <li class="divider"></li>
                                            <li><a href="about.html">Photo Gallery</a></li>
                                            <li class="divider"></li>
                                            <li><a href="typography.html">Short codes</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </ul>
                        </li>
                        <li><a href="{% url 'kyl:rssfeed' %}">News Feed</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Leaders<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'kyl:leadership_modi' %}">Modi</a></li>
                                <li class="divider"></li>
                                <li><a href="leadership.html">Gandhi</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'kyl:leadership_obama' %}">Obama</a></li>
                                <li class="divider"></li>
                                <li><a href="leadership.html">Ben Mark</a></li>
                                <li class="divider"></li>
                                <li><a href="leadership.html">Bruise Alley</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'kyl:contact' %}">Contact</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'kyl:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'kyl:login' %}">Login</a></li>
                        {% endif %}
                </ul>
                {% if user.is_authenticated %}

                    <p style="float:right; font-weight:bold;"> User : {{user.username}}</p>

                    {% else %}
                    <div class="social-icons">
                    <ul>
                        <li><a href="{% url 'kyl:login' %}" class="facebook"> </a></li>
                        <li><a href="{% url 'kyl:login' %}" class="p"> </a></li>
                        <li><a href="{% url 'kyl:login' %}" class="g"> </a></li>
                        <li><a href="{% url 'kyl:login' %}" class="twitter"> </a></li>
                    </ul>
                </div>
                    {% endif %}
                
            </div>
                <!--/.navbar-collapse-->
                <!--/.navbar-->
            </div>
            </nav>
        </div>
    </div>
   <!--/start-banner-->
 {% block content %} {% endblock %}
 <!--//end-main-->
 <!--/start-footer-section-->
            <div class="footer-section">
               <div class="container">
                    <div class="footer-grids">
                        <div class="col-md-4 footer-grid">
                        <h4>EDITOR PICKS</h4>
                          <div class="editor-pics">
                             <div class="col-md-3 item-pic">
                               <img src="{% static "images/f1.jpg" %}" class="img-responsive" alt=""/>

                               </div>
                                <div class="col-md-9 item-details">
                                    <h5 class="inner"><a href="#">More Than 120 ER Visits Linked To Synthetic WordPress In NYC...</a></h5>
                                      <div class="td-post-date">Nov 22, 2015</div>
                                 </div>
                                <div class="clearfix"></div>
                            </div>
                             <div class="editor-pics">
                             <div class="col-md-3 item-pic">
                               <img src="{% static "images/f2.jpg" %}" class="img-responsive" alt=""/>

                               </div>
                                <div class="col-md-9 item-details">
                                    <h5 class="inner"><a href="#">More Than 120 ER Visits Linked To Synthetic WordPress In NYC...</a></h5>
                                      <div class="td-post-date">Nov 22, 2015</div>
                                 </div>
                                <div class="clearfix"></div>
                            </div>
                             <div class="editor-pics">
                             <div class="col-md-3 item-pic">
                               <img src="{% static "images/f3.jpg" %}" class="img-responsive" alt=""/>

                               </div>
                                <div class="col-md-9 item-details">
                                    <h5 class="inner"><a href="#">More Than 120 ER Visits Linked To Synthetic WordPress In NYC...</a></h5>
                                      <div class="td-post-date">Nov 22, 2015</div>
                                 </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        <div class="col-md-4 footer-grid">
                            <h4>About Politics</h4>
                                <ul class="td-pb-padding-side">
                                    <li><a href="#">Mission</a></li>
                                    <li><a href="#">Organization</a></li>
                                    <li><a href="#">Our Achievements</a></li>
                                    <li><a href="#">Literature</a></li>
                                    <li><a href="#">Our Inspiration</a></li>
                                    <li><a href="#">Inc Sessions</a></li>
                                </ul>
                        </div>
                        <div class="col-md-4 footer-grid">
                                <h4>MEDIA RESOURCES</h4>
                                <ul class="td-pb-padding-side">
                                    <li><a href="#">Speeches</a></li>
                                    <li><a href="#">Public Forum</a></li>
                                    <li><a href="#">Photo Gallery</a></li>
                                    <li><a href="#">Books and Monographs</a></li>
                                </ul>
                                <div class="clearfix"></div>
                        </div>
                         <div class="col-md-4 footer-grid">
                                <h4>CONTACT US</h4>
                                <ul class="td-pb-padding-side">
                                    <li><a href="mailto:ashish.sareen2013@vit.ac.in?Subject=Contact%20Us" target="_top">Ashish Sareen</a></li>
                                    <li><a href="mailto:ashish.sareen2013@vit.ac.in?Subject=Contact%20Us" target="_top">Arpit Shringi</a></li>
                                    <li><a href="mailto:ashish.sareen2013@vit.ac.in?Subject=Contact%20Us" target="_top">Shubham Nair</a></li>
                                </ul>
                                <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
    <!--//end-footer-section-->
            <!--/start-copyright-section-->
             {% now "Y" as current_year %}
                <div class="copyright">
                          <p>&copy;  {{ current_year }} Politics. All Rights Reserved | Design by <a href="http:github.com/aksareen">aksareen</a> </p>
                    </div>


                <!--start-smoth-scrolling-->
                        <script type="text/javascript">
                                    $(document).ready(function() {
                                        /*
                                        var defaults = {
                                            containerID: 'toTop', // fading element id
                                            containerHoverID: 'toTopHover', // fading element hover id
                                            scrollSpeed: 1200,
                                            easingType: 'linear' 
                                        };
                                        */
                                        
                                        $().UItoTop({ easingType: 'easeOutQuart' });
                                        
                                    });
                                </script>
        <a href="{% url 'kyl:homepage' %}" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>


<!--JS-->
  <script type="text/javascript" src="{% static "js/bootstrap-3.1.1.min.js" %}"></script>

<!--//JS-->

</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% block title %}Know Your Leaders{% endblock %}
{%block extrahead %}
<script src='https://www.google.com/recaptcha/api.js?hl=en'></script>
{% endblock %}

{% block content %}
{% load staticfiles %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <center><font size="5">
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        <b style="color : red;" >{{ message }}</b>
    </li>
    </font></center>
    {% endfor %}
</ul>
{% endif %}
   <!--/start-banner
	<div class="banner1">
		<div class="container">
		</div>
	</div>
	//end-banner-->
	<!-- contact -->
	<div class="contact">
		<div class="container">
			<h3>How To Find Us</h3>
			<div class="contact-bottom">
				<iframe frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBpggT9zJ46sbB0tBofuxyPE2f_g2XQg1g&q=VIT+Vellore" allowfullscreen>
				</iframe>
			</div>
			<div class="col-md-4 contact-left">
				<h4>Address</h4>
				<p>D240 VIT University
					<span>Vellore,TN</span></p>
				<ul>
					<li>Free Phone :+1987654321</li>
					<li>Telephone :+1 078 4589 2456</li>
					<li>Fax :+1 078 4589 2456</li>
					<li><a href="mailto:ashish.sareen2013@vit.ac.in">ashish.sareen2013@vit.ac.in</a></li>
				</ul>
			</div>
			<div class="col-md-8 contact-left">
				{% if Error %}
                        <h4 align='center'><strong> {{Error}} </strong></h4>
                        {% endif %}
				<h4>Contact Form</h4>
				<form id="contactform" method="post" action="{% url 'kyl:contact' %}">
					{% csrf_token %}
					{% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <h4 align='center'> {{ error }} </h4>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}

					<input type="text" placeholder="Name" name="name" value="" required style="color:black">
					<input type="email" placeholder="Email" name="email" value="" required style="color:black">
					<input type="text" placeholder="Telephone" name="phone" value="" required style="color:black">
					<textarea type="text" placeholder="Message" name="textdata" required style="color:black"></textarea>
                    <input id="ContactSubmit" type="submit" value="Submit" >
					<input type="reset" value="Clear" >
                    <div class="form-group">
                        <span class="col-md-1 col-md-offset-2 text-center"></i></span>
                        <div class="col-md-8">
                         <div class="g-recaptcha" data-sitekey="6LcmmgwTAAAAAAjTdm709wN2xlBzAgND9hMPQnpU"></div>
                     </div>
                 </div>
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!-- //contact -->
	<!--/start-footer-section-->
{% endblock %}

templates/leadership_modi.html
{% extends "base.html" %}
{% block title %}Know Your Leaders{% endblock %}
{%block extrahead %}{% endblock %}

{% block content %}
{% load staticfiles %}
 {% if messages %}
        <center>
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </center>
 {% endif %}
   
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

 <a class="twitter-timeline" href="https://twitter.com/narendramodi" data-widget-id="719128267987374080">Tweets by @narendramodi</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<div class="fb-page" data-href="https://www.facebook.com/narendramodi/" data-tabs="timeline" data-width="450" data-height="600" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/narendramodi/"><a href="https://www.facebook.com/narendramodi/">Narendra Modi</a></blockquote></div></div>
 <!--/start-footer-section-->
{% endblock %}

templates/leadership_obama.html
{% extends "base.html" %}
{% block title %}Know Your Leaders{% endblock %}
{%block extrahead %}{% endblock %}

{% block content %}
{% load staticfiles %}
 {% if messages %}
        <center>
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </center>
 {% endif %}

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<a class="twitter-timeline" href="https://twitter.com/POTUS" data-widget-id="719288397894782976">Tweets by @POTUS</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<div class="fb-page" data-href="https://www.facebook.com/barackobama/" data-tabs="timeline" data-width="450" data-height="600" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/barackobama/"><a href="https://www.facebook.com/barackobama/">Barack Obama</a></blockquote></div></div>


{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>iVote Login</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    {% load staticfiles %}
        <script src="{% static "jquery/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/custom/styles.css" %}" rel="stylesheet">

        <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
<!--login modal-->
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
        {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><b style="color : red;">{{ message }}<b></li>
    {% endfor %}
  </ul>
  {% endif %}
          <h1 style="color : green;" class="text-center">KYL Login</h1>
      </div>
      <div class="modal-body">
          <form class="form col-md-12 center-block" name="loginform" accept-charset="UTF-8" enctype="application/x-www-form-urlencoded" method="post" action = "{% url 'kyl:login' %}">
            <div class="form-group">
              {% csrf_token %}
              <input type="text" class="form-control input-lg" placeholder="Username" name ="username" required >
            </div>
            <div class="form-group">
              <input type="password" class="form-control input-lg" placeholder="Password" name = "password" required >
            </div>
            <div class="form-group">
              <button id="Signin" class="btn btn-primary btn-lg btn-block">Sign In</button>
              <span class="pull-right"><a href="{% url 'kyl:signup' %}">Register</a></span><span><a href="#">Forgot Password?</a></span>
            </div>
          </form>
      </div>
      <div class="modal-footer">
          <div class="col-md-12">
          <button class="btn" data-dismiss="modal" id="cancelbutton" aria-hidden="true">Cancel</button>
          <script type="text/javascript">
     document.getElementById("cancelbutton").onclick = function () {
        location.href = "{% url 'kyl:homepage' %}";
    };
  </script>
      </div>  
      </div>
  </div>
  </div>
</div>

{% load staticfiles %}
<script src="{% static 'jquery/blockui.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() { 
    $('#Signin').click(function() { 
        $.blockUI({ css: { 
            border: 'none', 
            padding: '15px', 
            backgroundColor: '#000', 
            '-webkit-border-radius': '10px', 
            '-moz-border-radius': '10px', 
            opacity: .5, 
            color: '#fff' 
        } }); 
        setTimeout($.unblockUI, 2000); 
    }); 
});

</script>
  <!-- script references -->

  </body>
</html>

templates/rss.html
{% extends "base.html" %}
{% block title %}News Feed{% endblock %}
{%block extrahead %}{% endblock %}

{% block content %}
{% load staticfiles %}
 {% if messages %}
        <center>
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </center>
 {% endif %}

 <style type="text/css">
#contactform input[type="text"]
{
  margin-right: 20px;
  width: 40%;
}
#contactform input[type="submit"], input[type="reset"]
{
  margin-right: 20px;
  width: 40%;
}
 </style>


<div class="col-md-8 contact-left">

        <h4>Latest News Feed</h4>
        <form id="contactform" method="get" action="{% url 'kyl:rssfeed' %}">

          <input name="includess" type="text" placeholder="Include" value="" style="font-weight:bold; color:black;">
          <input name="excludess" type="text" placeholder="Exclude" value="" style="font-weight:bold; color:black;">
          <br><br><br>
          <input id="ContactSubmit" type="submit" value="Submit" >
          <input type="reset" value="Clear" >

          
        </form>

        <br>
      </div>

<script type="text/javascript">
document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');
</script>
<script type="text/javascript">

(function() {

var params = {rssmikle_url: "http://www.ibnlive.com/rss/politics.xml|http://www.firstpost.com/politics/feed|http://www.ft.com/rss/world/asiapacific/india|http://www.thehindu.com/business/Economy/?service=rss|http://feeds.feedburner.com/News-People",rssmikle_frame_width: "620",rssmikle_frame_height:"800",frame_height_by_article: "8",rssmikle_target: "_blank",rssmikle_font: "Arial, Helvetica, sans-serif",rssmikle_font_size: "18",rssmikle_border: "on",responsive: "on",rssmikle_css_url: "",text_align: "left",text_align2: "left",corner: "on",scrollbar: "on",autoscroll: "on",scrolldirection: "up",scrollstep: "5",mcspeed: "20",sort: "New",rssmikle_title: "on",rssmikle_title_sentence: "Latest News",rssmikle_title_link: "",rssmikle_title_bgcolor: "#0066FF",rssmikle_title_color: "#FFFFFF",rssmikle_title_bgimage: "",rssmikle_item_bgcolor: "#FFFFFF",rssmikle_item_bgimage: "",rssmikle_item_title_length: "120",rssmikle_item_title_color: "#0066FF",rssmikle_item_border_bottom: "on",rssmikle_item_description: "on",item_link: "off",rssmikle_item_description_length: "800",rssmikle_item_description_color: "#666666",rssmikle_item_date: "gl1",rssmikle_timezone: "Etc/GMT",datetime_format: "%b %e, %Y %l:%M %p",item_description_style: "text+tn",item_thumbnail: "full",item_thumbnail_selection: "auto",article_num: "35",rssmikle_item_podcast: "off",keyword_inc:"" ,keyword_exc:"" };

{% if includess %}
params['keyword_inc'] = "{{includess}}";
{% endif %}
{% if excludess %}
params['keyword_exc'] = "{{excludess}}";
{% endif %}

feedwind_show_widget_iframe(params);})();
</script>
<div style="font-size:10px; text-align:center; "><a href="http://github.com/aksareen/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a></div>

 <!--//end-main-->
 <!--/start-footer-section-->
{% endblock %}